name = "uuid256-edge-example"
main = "worker.mjs"
compatibility_date = "2025-06-04"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
rules = [{ type = "CompiledWasm", globs = ["**/*.wasm"], fallthrough = true }]
