name: test-lib

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  ci:
    name: ci for lib
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/lib
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno 🦕
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Show Deno version
        run: |
          deno --version

      - name: Run Deno fmt
        run: |
          deno fmt --check
        id: fmt

      - name: Run Deno tests
        run: |
          deno test
        id: test
